### PR TITLE
updating packages

### PR DESCRIPTION
**Pull request by chipcullen**
I noticed that Prism lighthouse scores were different from the scores in Chrome dev tools. It seems that prism's CLI has fallen behind a bit. This PR simply updates it.

### CODE REVIEW

**Comment by nlicitra** [comment]
It looks like the new version of `lighthouse` doesn't have `time-to-first-byte` as an audit key anymore or it's under a new name. I'll try to figure out whats going on this afternoon.

**Comment by nlicitra** [comment]
@chipcullen in lighthouse version `6.0.0`, the `time-to-first-byte` audit was renamed to `server-response-time`. I updated the key and pushed it up but wanted to call out that this will generate a new key `pbsorg.prod.videoplayback.lighthouse.serverResponseTime` instead of `pbsorg.prod.videoplayback.lighthouse.timeToFirstBye` so datadog will think its a brand new metric.

**Comment by chipcullen** [comment]
@nlicitra ah - thanks for looking into this! good to know the metric updated. That wasn't one of the ones we were watching closely, so I don't think there is downstream changes to make.

**Review by nlicitra — APPROVED** [review]
Was able to successfully execute a dry run so looking good on my end!

**Comment by chipcullen** [comment]
@nlicitra I will leave it to you to merge 💪

**Pull request merged**
